# Generated by Django 6.0 on 2025-12-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='emp_data',
        ),
    ]
