# Generated by Django 6.0 on 2025-12-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_emp_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.AddField(
            model_name='employee',
            name='empid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
