# Generated by Django 6.0 on 2026-01-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_employee_empid'),
    ]

    operations = [
        migrations.CreateModel(
            name='passwordrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('classotp', models.CharField(max_length=6)),
            ],
        ),
    ]
