# Generated by Django 6.0 on 2026-01-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_passwordrest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Password',
            field=models.CharField(default=12362, max_length=6),
            preserve_default=False,
        ),
    ]
